import { NextResponse } from "next/server";
import OpenAI from "openai";

// Helper to simulate agent-specific reasoning steps
const getReasoningSteps = (agentId: string) => {
  const common = [
    "Spinning up autonomous sandbox container...",
    "Analyzing request semantic patterns...",
  ];

  switch (agentId) {
    case "content-agent":
      return [
        ...common,
        "Ingesting marketing hooks and keyword trends...",
        "Drafting structural outline (Introduction, Hook, Body, CTA)...",
        "Refining vocabulary and brand tone variables...",
        "Executing SEO optimization audits...",
        "Finalizing copy drafts...",
      ];
    case "design-agent":
      return [
        ...common,
        "Extracting visual themes and brand semantics...",
        "Constructing typographic grid hierarchies...",
        "Formulating cohesive hex color palettes...",
        "Designing component wireframes and styling parameters...",
        "Polishing visual identity specifications...",
      ];
    case "coding-agent":
      return [
        ...common,
        "Checking dependency structures and imports...",
        "Structuring modular React/TypeScript functions...",
        "Injecting responsive Tailwind styling classes...",
        "Verifying state hooks and rendering lifecycles...",
        "Running strict linter check & code formatter...",
      ];
    case "resume-agent":
      return [
        ...common,
        "Scanning resume text against ATS parser indexes...",
        "Restructuring experience bullets for maximum metric impact...",
        "Drafting career highlight summaries and key accomplishments...",
        "Aligning formatting to modern recruiting standards...",
        "Reviewing action verbs and style flow...",
      ];
    default:
      return [
        ...common,
        "Generating solution outline...",
        "Executing core synthesis logic...",
        "Formatting final output...",
      ];
  }
};

// Fallback high-fidelity content generators when OpenAI API key is missing
const generateFallbackOutput = (agentId: string, prompt: string): string => {
  const p = prompt.toLowerCase();

  if (agentId === "content-agent") {
    if (p.includes("blog") || p.includes("article")) {
      return `# The Future of Autonomous Freelance Networks: Web3 & AI Agents

*Generated by Scribe.AI - Creative Marketing Expert*

Decentralized workforces are transitioning from human-only networks to hybrid ecosystems driven by **autonomous AI agents**. As organizations seek immediate, high-quality output without management overhead, the marriage of Web3 and LLMs presents a paradigm shift.

## 1. The Autonomous Economy
AI agents are no longer just chatbots; they are sovereign economic entities. By holding cryptocurrency keys (specifically on fast, low-fee chains like **Avalanche**), these agents can pay for API costs, trade compute, and receive payments for services rendered directly from clients.

## 2. Eliminating Friction with Smart Contracts
Traditional platforms charge up to 20% in fees and take days to clear payments. With Avalanche C-Chain or Fuji Testnet, escrow contracts clear payments instantly upon task completion, verifying delivery via cryptographic proofs.
- **Fees**: < $0.01 per transaction.
- **Speed**: Sub-second finality.
- **Sovereignty**: No central gatekeepers.

## 3. The Multi-Agent Orchestrator
In the near future, you won't hire just one agent. You will hire an orchestrator agent that subcontracts a developer agent, an illustrator agent, and a copywriter agent. They will collaborate, resolve merges, and deliver a full-fledged product autonomously.

> "AI is the engine, but Blockchain is the rails. Together, they form the first frictionless digital labor market."

---
*Task parameters: Prompt: "${prompt}" | Copy and use under MIT license.*`;
    }

    if (p.includes("caption") || p.includes("instagram") || p.includes("ad")) {
      return `### 🚀 Cyberpunk Social Media Campaign Kit
*Generated by Scribe.AI*

Here are 3 high-converting copy variations for your campaign based on your request:

#### Option 1: The Hook (Instagram/Twitter)
"Stop paying monthly fees for tools that sleep. 🤫 

Meet the first generation of autonomous AI freelancers that work 24/7, compile in milliseconds, and get paid in AVAX. Faster. Cheaper. Sovereign. 

Tap the link in bio to hire your first developer agent today. 💻⚡ #Web3 #AIAgents #Avalanche #Solidity"

#### Option 2: The Direct Pitch (LinkedIn)
"The future of work isn't remote—it's autonomous. 

We are officially entering the agentic economy. Today, we're introducing Nexa-Develop, an AI Agent capable of writing, compiling, testing, and deploying Next.js components autonomously. Payment? Settled on-chain in Avalanche AVAX with instant escrow release.

No interviews. No delays. Just clean, optimized code. 

Are you ready to hire your first digital employee? 🤖"

#### Option 3: Short Ad Copy (Meta/Google Ads)
**Headline**: Hire Autonomous AI Developers.
**Body**: Instant deliverables. Zero management. Pay with AVAX testnet. Tap to explore our marketplace and delegate your coding backlog today.`;
    }

    return `### 📝 Creative Content Deliverable
*Generated by Scribe.AI - Creative Marketing Expert*

Here is the customized copy developed for your prompt:

"${prompt}"

#### Core Campaign Concepts:
- **Brand Position**: High-tech, futuristic, efficiency-driven.
- **Target Persona**: Web3 developers, startup founders, and technical managers.
- **Call to Action**: "Deploy agent on-chain."

#### Copy Draft:
Our AI agents work round the clock to deliver high-quality outputs. By harnessing advanced LLM reasoning, this content is optimized for clarity, engagement, and conversion metrics. Adjust as needed for specific platform guidelines.`;
  }

  if (agentId === "design-agent") {
    if (p.includes("name") || p.includes("startup")) {
      return `### 💡 Startup Naming & Brand Concepts
*Generated by Aura.AI - Creative Design Consultant*

Based on your prompt, here are 5 naming ideas complete with brand semantics, domain strategies, and visual concepts:

1. **AetherNode**
   - *Theme*: Cloud, Web3 routing, ethereal intelligence.
   - *Color Accent*: Neon Purple (#7B61FF).
   - *Vibe*: Premium SaaS developer infrastructure.

2. **NovusForge**
   - *Theme*: Innovation, autonomous building, steel-like reliability.
   - *Color Accent*: Cyber Cyan (#00F0FF).
   - *Vibe*: High-performance compilers or developer toolkits.

3. **CrypticFlow**
   - *Theme*: Privacy, cryptography, streamlined pipelines.
   - *Color Accent*: Acid Green (#39FF14).
   - *Vibe*: Decentralized finance or zero-knowledge scaling systems.

4. **Kortex.AI**
   - *Theme*: Deep neural layers, structural logic, executive agents.
   - *Color Accent*: Bright Pink (#FF007A).
   - *Vibe*: Collaborative multi-agent productivity dash.

5. **FujiMelt**
   - *Theme*: Avalanche node layer, warm branding, fun UI.
   - *Color Accent*: Coral Red (#FF5C00).
   - *Vibe*: Developer community portal or NFT marketplace.`;
    }

    if (p.includes("palette") || p.includes("color") || p.includes("theme")) {
      return `### 🎨 Premium UI Style Guide & Color Palette
*Generated by Aura.AI*

Here is a modern dark-mode style guide matching your branding request:

#### 1. Color Palette (Cyber Neon Theme)
- **Deep Space (Background)**: \`#030014\` - A rich, deep dark blue-purple base.
- **Card Backdrop**: \`#0A081C\` (opacity 0.7) - Semitransparent slate-purple.
- **Cyber Purple (Primary Accent)**: \`#7B61FF\` - Glowing purple for main CTAs and highlights.
- **Cyber Neon Blue (Secondary Accent)**: \`#00F0FF\` - Vibrant cyan for active statuses and subheaders.
- **Hot Pink (Warning/Alert)**: \`#FF007A\` - Used for critical CTAs and high-importance badges.

#### 2. Typography Recommendation
- **Headings**: *Outfit* (Google Fonts) - Clean, round geometric shapes that look modern and premium.
- **Body Text**: *Inter* - Extremely legible at small sizes.
- **Code/Stats**: *JetBrains Mono* - Monospaced character spacing matching technical applications.

#### 3. Shadow & Glassmorphism Spec
\`\`\`css
.neon-glow-card {
  background: rgba(10, 8, 28, 0.45);
  backdrop-filter: blur(12px);
  border: 1px solid rgba(123, 97, 255, 0.15);
  box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37), 0 0 15px rgba(123, 97, 255, 0.2);
}
\`\`\``;
    }

    return `### 🎨 Creative Branding Wireframe Mock
*Generated by Aura.AI - Creative Design Consultant*

For your requested prompt: "${prompt}"

#### Layout Recommendations:
- Use a **two-column layout** on desktop, collapsing to a single column on mobile.
- Left column: Bold geometric headings with a gradient accent.
- Right column: Interactive preview panel showing outputs.
- Incorporate subtle hover translations (e.g. \`transform: translateY(-4px)\`) to make buttons feel alive.`;
  }

  if (agentId === "coding-agent") {
    if (p.includes("hook") || p.includes("custom")) {
      return `### 💻 Custom React Hook: \`useLocalStorage\` (TypeScript)
*Generated by Nexus.AI - Senior Software Engineer*

Here is a fully typed, SSR-safe custom React hook to synchronize state with \`localStorage\`.

\`\`\`typescript
import { useState, useEffect, useCallback } from "react";

export function useLocalStorage<T>(key: string, initialValue: T) {
  // Read value from localStorage, fallback if server-side
  const readValue = useCallback((): T => {
    if (typeof window === "undefined") {
      return initialValue;
    }

    try {
      const item = window.localStorage.getItem(key);
      return item ? (JSON.parse(item) as T) : initialValue;
    } catch (error) {
      console.warn(\`Error reading localStorage key "\${key}":\`, error);
      return initialValue;
    }
  }, [key, initialValue]);

  const [storedValue, setStoredValue] = useState<T>(readValue);

  // Set value both in state and localStorage
  const setValue = useCallback((value: T | ((val: T) => T)) => {
    try {
      const valueToStore = value instanceof Function ? value(storedValue) : value;
      setStoredValue(valueToStore);
      
      if (typeof window !== "undefined") {
        window.localStorage.setItem(key, JSON.stringify(valueToStore));
      }
    } catch (error) {
      console.warn(\`Error setting localStorage key "\${key}":\`, error);
    }
  }, [key, storedValue]);

  // Synchronize when key changes
  useEffect(() => {
    setStoredValue(readValue());
  }, [key, readValue]);

  return [storedValue, setValue] as const;
}
\`\`\`

#### How to use:
\`\`\`tsx
const [theme, setTheme] = useLocalStorage<"light" | "dark">("theme", "dark");
\`\`\``;
    }

    return `### 💻 Next.js React Component: Glassmorphic Hero Card
*Generated by Nexus.AI - Senior Software Engineer*

Here is a premium Tailwind-styled Hero Component for your application.

\`\`\`tsx
import React from 'react';
import { motion } from 'framer-motion';

interface HeroCardProps {
  title: string;
  subtitle: string;
  ctaText: string;
  onCtaClick?: () => void;
}

export const GlassmorphicHero: React.FC<HeroCardProps> = ({
  title,
  subtitle,
  ctaText,
  onCtaClick
}) => {
  return (
    <div className="relative overflow-hidden rounded-2xl border border-purple-500/20 bg-slate-900/40 p-8 backdrop-blur-xl shadow-2xl">
      {/* Absolute glow accent */}
      <div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-cyan-500/20 blur-3xl pointer-events-none" />
      
      <div className="relative z-10 flex flex-col gap-4">
        <span className="text-xs font-semibold tracking-widest text-cyan-400 uppercase">
          SYSTEM_DEPLOYED
        </span>
        <h1 className="text-3xl font-extrabold text-white sm:text-4xl">
          {title}
        </h1>
        <p className="text-slate-300 text-sm leading-relaxed max-w-lg">
          {subtitle}
        </p>
        
        <button
          onClick={onCtaClick}
          className="mt-4 w-fit rounded-xl bg-gradient-to-r from-purple-500 to-cyan-500 px-6 py-3 text-sm font-semibold text-white shadow-lg transition-transform hover:scale-105 active:scale-95"
        >
          {ctaText}
        </button>
      </div>
    </div>
  );
};
\`\`\`

*Verified compiler status: 0 errors | TypeScript 5.4 compliant.*`;
  }

  if (agentId === "resume-agent") {
    if (p.includes("summary") || p.includes("bio")) {
      return `### 📄 High-Impact ATS Professional Summary
*Generated by CareerPath.AI - Professional Career Coach*

Copy and paste this resume summary section to capture recruiters' attention instantly.

#### Summary Draft:
> "Result-oriented Senior Frontend Engineer with **5+ years of experience** specializing in React, Next.js, and TypeScript, building responsive SaaS applications. Proven track record of improving web performance metrics (LCP/FID) by **42%** and migrating legacy monolithic apps to serverless architectures, cutting cloud computing costs by **18%**. Expert in collaborating within agile teams, mentoring junior staff, and integrating smart contracts (Web3/ethers.js) to deliver secure user-centric web applications."

#### Bullet Point Enhancements:
- **Before**: "Responsible for writing React components."
- **After**: "Designed and implemented a library of **30+ reusable React/TypeScript components**, accelerating front-end feature delivery speed by **25%**."
- **Before**: "Worked on fixing bugs and issues."
- **After**: "Resolved **120+ legacy UI rendering bugs** and implemented test automation suites, increasing code coverage to **85%** and reducing production critical bugs."`;
    }

    return `### ✉️ Persuasive Cover Letter Draft
*Generated by CareerPath.AI - Professional Career Coach*

Dear Hiring Manager,

I am writing to express my strong interest in the open position. With a robust background in developing web interfaces, coupled with my passion for creating intuitive, performant user experiences, I am confident in my ability to make a significant impact at your team.

During my previous tenure, I was instrumental in leading front-end migration pipelines. We implemented Next.js 14 App Router, cutting server response delays by 35% and upgrading our overall search rank positioning. 

I am particularly excited about your company's focus on autonomous systems. I look forward to bringing my expertise in React, Web3 wallets, and responsive design systems to your core products.

Thank you for your time and consideration.

Sincerely,
[Your Name]
[Your Contact Link]`;
  }

  return `### 🤖 Task Completed Successfully
*Generated by Agentic Model*

Here is the completed output for your request:
"${prompt}"

#### Technical parameters:
- Output formatted: Markdown.
- Safety filter checked: Yes.
- Semantic accuracy: 98%.`;
};

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { agentId, prompt, budget } = body;

    if (!agentId || !prompt) {
      return NextResponse.json(
        { error: "agentId and prompt are required parameters." },
        { status: 400 }
      );
    }

    const openaiKey = process.env.OPENAI_API_KEY;
    const reasoningSteps = getReasoningSteps(agentId);

    // If API Key is present, try invoking the actual OpenAI API
    if (openaiKey && openaiKey !== "YOUR_OPENAI_API_KEY_HERE") {
      try {
        const openai = new OpenAI({ apiKey: openaiKey });

        // Get system prompt based on agent
        let systemPrompt = "You are a professional assistant.";
        if (agentId === "content-agent") {
          systemPrompt = "You are Scribe.AI, a creative marketing copywriter and SEO blogger. Write engaging, persuasive, and beautifully structured marketing copy. Use markdown.";
        } else if (agentId === "design-agent") {
          systemPrompt = "You are Aura.AI, a premium startup branding consultant and UI designer. Provide startup naming suggestions, hex palettes, style wireframe layout ideas, and UX tips. Use markdown.";
        } else if (agentId === "coding-agent") {
          systemPrompt = "You are Nexus.AI, a senior React and TypeScript software developer. Write clean, modular, and syntax-correct code blocks. Include concise explanations and standard Tailwind classes. Use markdown.";
        } else if (agentId === "resume-agent") {
          systemPrompt = "You are CareerPath.AI, a professional career coach and ATS resume optimizer. Help write summaries, letters, and portfolios. Use markdown and focus on metrics and achievements.";
        }

        const completion = await openai.chat.completions.create({
          model: "gpt-3.5-turbo", // Cost-effective fast model
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: `Prompt: ${prompt}\nBudget for this task: ${budget} AVAX.` },
          ],
          temperature: 0.7,
          max_tokens: 800,
        });

        const textOutput = completion.choices[0]?.message?.content || "No output generated.";

        return NextResponse.json({
          success: true,
          output: textOutput,
          reasoningSteps,
        });
      } catch (err: unknown) {
        const errMsg = err instanceof Error ? err.message : String(err);
        console.error("OpenAI API call failed, falling back to mock:", errMsg);
        // Fallback on OpenAI error
        const fallback = generateFallbackOutput(agentId, prompt);
        return NextResponse.json({
          success: true,
          output: fallback,
          reasoningSteps,
          isMock: true,
          notice: "OpenAI call failed. Returned high-fidelity mock response instead.",
        });
      }
    }

    // No API Key, use high-fidelity mock generator
    // Simulate API delay (e.g. 1 second) to let the loading steps shine
    await new Promise((resolve) => setTimeout(resolve, 800));
    
    const fallback = generateFallbackOutput(agentId, prompt);
    return NextResponse.json({
      success: true,
      output: fallback,
      reasoningSteps,
      isMock: true,
    });
  } catch (error: unknown) {
    const errMsg = error instanceof Error ? error.message : "Internal Server Error";
    console.error("API error:", error);
    return NextResponse.json(
      { error: errMsg },
      { status: 500 }
    );
  }
}
